server:
  port: 11111

bus:
  datasource:
    username: root
    password: xxxxx
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:9001/app-bus?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false

user:
  datasource:
    username: root
    password: xxxxx
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxx:9001/app-user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false